version: 2
jobs:
  build:

    docker:
      - image: circleci/node:8.9.4
        environment:
          - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
          - TERM: xterm
          - YARN_VERSION: 1.3.2
          - NODE_VERSION: 8.9.1
          - NODE_ENV: development

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install node deps
          command: yarn install --network-concurrency 1

      # run tests!
      - run: yarn test

      # - run:
      #     command: |
      #       yarn android:release:generate

      # - store_artifacts:
      #     path: android/app/build/outputs/apk/
      #     destination: android
      # - store_artifacts:
      #     path: android/app/build/reports
      #     destination: android
